# Generated by Django 3.2.12 on 2023-05-11 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_rename_time_recipe_cooking_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='description',
            new_name='text',
        ),
    ]
