# Generated by Django 3.2.12 on 2023-05-15 12:24

from django.db import migrations, models
import recipe.validators


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_auto_20230515_1258'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='recipe',
            name='unique_recipe',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.IntegerField(help_text='Введите время приготовления в минутах', validators=[recipe.validators.validate_time], verbose_name='Время приготовления'),
        ),
    ]
