# Generated by Django 3.2.12 on 2023-05-15 14:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('recipe', '0003_auto_20230515_1524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='amount',
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='amount',
            field=models.IntegerField(default=0, verbose_name='Количество'),
            preserve_default=False,
        ),
    ]
