# Generated by Django 3.2.12 on 2023-05-11 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_rename_description_recipe_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='picture',
            new_name='image',
        ),
    ]
