# Generated by Django 3.2.12 on 2023-05-13 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0007_rename_units_ingredient_measurement_unit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='qty',
            new_name='amount',
        ),
    ]
